java.lang.NullPointerException: Cannot invoke "jdk.internal.access.JavaLangAccess.getUTF16Char(byte[], int)" because "jdk.internal.util.ArraysSupport.JLA" is null #56